---
- name: Configure keyboard model
  ansible.builtin.lineinfile:
    path: /etc/default/keyboard
    regexp: "^XKBMODEL="
    line: 'XKBMODEL="{{ keyboard_layout_model }}"'

- name: Configure keyboard layout
  ansible.builtin.lineinfile:
    path: /etc/default/keyboard
    regexp: "^XKBLAYOUT="
    line: 'XKBLAYOUT="{{ keyboard_layout_layout }}"'

- name: Configure keyboard variant
  ansible.builtin.lineinfile:
    path: /etc/default/keyboard
    regexp: "^XKBVARIANT="
    line: 'XKBVARIANT="{{ keyboard_layout_variant }}"'

- name: Configure keyboard options
  ansible.builtin.lineinfile:
    path: /etc/default/keyboard
    regexp: "^XKBOPTIONS="
    line: 'XKBOPTIONS="{{ keyboard_layout_options }}"'

- name: Configure keyboard backspace
  ansible.builtin.lineinfile:
    path: /etc/default/keyboard
    regexp: "^BACKSPACE="
    line: 'BACKSPACE="{{ keyboard_layout_backspace }}"'
